[package]
name = "searchup"
version = "0.1.0"
edition = "2024"
authors = ["Snehil Khokhar <snehil.khokhar45@gmail.com>"]
description = "A fast, parallel CSV analyzer CLI tool for detecting missing values and inspecting datasets"
license = "MIT OR Apache-2.0"
repository = "https://github.com/khokharsnehil45/searchup"
keywords = ["csv", "cli", "parallel", "data-analysis", "data-quality"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
rayon = "1.10"

[dev-dependencies]
tempfile = "3.10"
